[tox]
requires =
    tox-uv
    tox-gh
env_list =
    py{310,311,312,313,314}-dj{52}
    py{312,313,314}-dj{60,61}
skip_missing_interpreters = true

[gh]
python =
    3.10 = py310-dj52
    3.11 = py311-dj52
    3.12 = py312-dj{52,60,61}
    3.13 = py313-dj{52,60,61}
    3.14 = py314-dj{52,60,61}

[testenv]
package = editable
dependency_groups = dev
setenv =
    DJANGO_SETTINGS_MODULE = secretballot.tests.settings
deps =
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
commands =
    pytest {posargs}
