# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 08:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=50)),
                ("vote", models.SmallIntegerField(choices=[(1, b"+1"), (-1, b"-1")])),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.ContentType"),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set([("token", "content_type", "object_id")]),
        ),
    ]
