# Generated by Django 2.2.3 on 2019-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.TextField(),
        ),
    ]
